### ISSUE TITLE
Rendering issue in Admin REST API docs

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apk#108]
**Description:**
The following was identified during a call with Krishan.

There is a rendering issue in Admin REST API docs [1]. 
- All the APIs after Tenant config Schema does not appear in the left menu, but they appear if we explicitly search for it. 

### Screenshots
**Not in left menu**

<img width="1728" alt="Screenshot 2023-03-20 at 5 32 19 PM" src="https://user-images.githubusercontent.com/5195851/226333776-aa7fd404-1501-4472-a682-fa224fd2ae22.png">

**Appears when searched for**

<img width="1728" alt="Screenshot 2023-03-20 at 5 32 34 PM" src="https://user-images.githubusercontent.com/5195851/226333839-02335a3c-8d54-44cc-8a42-3fef53ed8aec.png">

[1] https://apk.docs.wso2.com/en/latest/catalogs/api-reference-admin/

**Comment by Mariangela** [comment]
When you check in https://editor.swagger.io/ it renders ok. So does not look like there is an issue with the way it is defined.

<img width="1728" alt="Screenshot 2023-03-20 at 4 45 53 PM" src="https://user-images.githubusercontent.com/5195851/226334095-a1754eec-f78c-4348-843f-c291f8f0546d.png">

**Comment by Mariangela** [comment]
Moved the Organization code higher up in the YAML and it shows but then it removes some of the menus that were previously visible
<img width="1727" alt="Screenshot 2023-03-20 at 5 40 23 PM" src="https://user-images.githubusercontent.com/5195851/226335225-dcb52fe9-52c7-4f98-9b13-79a55c03e128.png">





### Screenshots
**Not in left menu**

<img width="1728" alt="Screenshot 2023-03-20 at 5 32 19 PM" src="https://user-images.githubusercontent.com/5195851/226333776-aa7fd404-1501-4472-a682-fa224fd2ae22.png">

**Appears when searched for**

<img width="1728" alt="Screenshot 2023-03-20 at 5 32 34 PM" src="https://user-images.githubusercontent.com/5195851/226333839-02335a3c-8d54-44cc-8a42-3fef53ed8aec.png">

**Renders ok in https://editor.swagger.io/**
<img width="1728" alt="Screenshot 2023-03-20 at 4 45 53 PM" src="https://user-images.githubusercontent.com/5195851/226334095-a1754eec-f78c-4348-843f-c291f8f0546d.png">


[1] https://apk.docs.wso2.com/en/latest/catalogs/api-reference-admin/

**Comment by Mariangela** [comment]
### Update

- Had a discussion with Jerard. 
- He confirmed that it looks like there is an issue with the left menu.
- He is investigating as to how this can be fixed.

**Comment by Mariangela** [comment]
@jeradrutnam , thanks loads for helping to fix this issue. Really appreciate your help.

<img width="1728" alt="Screenshot 2023-03-20 at 6 32 30 PM" src="https://user-images.githubusercontent.com/5195851/226346872-2a105fc6-3434-4009-81ad-41f805efafa2.png">

**Comment by jeradrutnam** [comment]
> 
> @jeradrutnam , thanks loads for helping to fix this issue. Really appreciate your help.
> 
> <img width="1728" alt="Screenshot 2023-03-20 at 6 32 30 PM" src="https://user-images.githubusercontent.com/5195851/226346872-2a105fc6-3434-4009-81ad-41f805efafa2.png">
> 

No prob @Mariangela 🙂
