### ISSUE TITLE
[Quick-start] Error got while executing dependecy update

### ISSUE THREAD

**Issue by Thumimku** [wso2/docs-apk#193]
**Description:**
While following https://apk.docs.wso2.com/en/latest/get-started/quick-start-guide/  I got the following issue when executing step 2.
```
Error: Chart.yaml file is missing

```
There was a query in discord APK channel also. Link: https://discordapp.com/channels/955510916064092180/1113443798773682207/1113443798773682207

**Comment by CrowleyRajapakse** [comment]
this is resolved
