### ISSUE TITLE
Same idea mentioned multiple times

### ISSUE THREAD

**Issue by GihanAyesh** [wso2/docs-apk#278]
**Description:**
In the [1], the same context is repeated in the first three paragraphs of Rate Limiting Overview. It would be better to remove the redundant content.

[1] https://apk.docs.wso2.com/en/latest/create-api/rate-limiting/rate-limiting-policy-overview/

**Comment by CrowleyRajapakse** [comment]
current description seems okay for me, will be revisited if needed
