### ISSUE TITLE
Doc page should clearly mention how to try out use cases from begin to end

### ISSUE THREAD

**Issue by rmsamitha** [wso2/docs-apk#295]
**Description:**
For an example "Add Basic Auth Backend Security via CRs" docs describes the insight on the topic.
But I believe it is better if we document the full scenario, from beginning to end with clear steps so that somebody can try out the scenario easily. We have followed this approach in APIM in most of the times. e.g. https://apim.docs.wso2.com/en/4.1.0/design/endpoints/endpoint-security/basic-auth/

The steps and concept behind might be simple, but it would be nice if we follow the above mentioned approach so that evaluators will find it well convenient and learn stuff quickly, since this is a very common APIM use case.
This idea may apply to most of the other common APIM use cases too.

**Comment by msm1992** [comment]
Fixed with https://github.com/wso2/docs-apk/pull/383
