### ISSUE TITLE
Update Jenkins build for latest Mkdocs

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apk#57]
**Description:**
Get the Jenkins build to work with Mkdocs 1.4.2 and Python 3.11 or 3.9.

**Comment by Mariangela** [comment]
[build-script-b98.txt](https://github.com/wso2/docs-apk/files/10940477/build-script-b98.txt)

@chanaka3d , note that this is the build script that Shani was working on when trying to fix the APK build script to support the latest Mkdocs version. But this build script was also failing. She said that after fixing it multiple times and clearing out the errors, that now it was failing due to a template issue.

**Comment by chanaka3d** [comment]
Since the docs-apk-dev build is working fine we can close this issue.
