### ISSUE TITLE
Automating process of maintaining REST API Catalogs

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apk#72]
**Description:**

### Existing method
When adding REST API catalogs we carryout the following steps:
1. Download the YAML from the product APK repo (e.g., [2])
2. Save it in en/docs/catalogs directory in the docs-apk repo
3. Refer to the YAML in the respective MD file. (e.g., en/docs/catalogs/api-reference-developer-portal.md)

         Example:
         ```
         ---
         template: templates/redoc.html
         ---

         <redoc spec-url='{{base_path}}/catalogs/devportal-api.yaml'></redoc>
         <script src="https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js"> </script>
         ```

      The REST API catalog will rendered as expected. (e.g., https://apk.docs.wso2.com/en/latest/catalogs/api-reference-developer-portal/)

<img width="1728" alt="Screenshot 2023-03-20 at 11 43 19 AM" src="https://user-images.githubusercontent.com/5195851/226261170-0d654df5-207c-4a6d-b694-9fab2be90fd3.png">

**Disadvantage of the above method** 
- Every time changes are done to the REST API YAML file in the APK product repo (wso2/apk [1]), we have to manually copy the YAML file and and add it to the  APK  docs repo (wso2/docs-apk [2] repo). 
- There is a high possibility that the content in the APK docs will be outdated because APK devs may not remember alert when changes are done in the REST API YAML docs.

[1] https://github.com/wso2/apk
[2] https://github.com/wso2/docs-apk

### Proposed Fix
@sanjeewa-malalgoda suggested to also get the https://github.com/wso2/apk repo to build as well in the APK build script [3]. So that we can automate the process.

### Note
When trying to add the APK product repo GitHub URL directly in the APK docs repo MD file the REST API Catalog does not work.

```
---
template: templates/redoc.html
---

<redoc spec-url='[{{base_path}}/catalogs/devportal-api.yaml](https://github.com/wso2/apk/blob/main/devportal/devportal-domain-service/ballerina/resources/devportal-api.yaml)'></redoc>
<script src="https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js"> </script>
```

<img width="1727" alt="Screenshot 2023-03-10 at 1 36 06 PM" src="https://user-images.githubusercontent.com/5195851/224272695-23f580b6-e4b1-4574-9143-cd0f79916ff9.png">

[1] en/docs/catalogs/api-reference-developer-portal.md
[2] https://github.com/wso2/apk/blob/main/devportal/devportal-domain-service/ballerina/resources/devportal-api.yaml
[3] https://wso2.org/jenkins/job/docs/job/docs-apk/configure

**Comment by chanaka3d** [comment]
This issue is fixed in the dev environment. Please check and confirm.
